theme: jekyll-theme-modernist
title: دیلیمیز سایتې
fontname: Amiri-Regular
fontsize: 18
fontttf: /assets/Amiri-Regular.ttf
fonteot: /assets/Amiri-Regular.eot
fontwoff: /assets/Amiri-Regular.woff
fontwoff2: /assets/Amiri-Regular.woff2
 
