theme: jekyll-theme-modernist
title: Dilimiz
description: Turkic literature
fontname: Amiri-Regular
fontsize: 18
fontttf: /assets/Amiri-Regular.ttf
fonteot: /assets/Amiri-Regular.eot
fontwoff: /assets/Amiri-Regular.woff
fontwoff2: /assets/Amiri-Regular.woff2
author: Arslan
permalink: /blog/:year/:month/:day/:title
google_analytics: G-HF5NYF5MWQ
