theme: jekyll-theme-modernist
title: Welcome!
description: Amir Arslan Haghrah | امیر ارسلان حق ره
logo: /assets/avatar.png
fontname: Amiri-Regular
fontsize: 18
fontttf: /assets/Amiri-Regular.ttf
fonteot: /assets/Amiri-Regular.eot
fontwoff: /assets/Amiri-Regular.woff
fontwoff2: /assets/Amiri-Regular.woff2
author: Arslan
permalink: /blog/:year/:month/:day/:title

 
